apiVersion: apps/v1      
kind: Deployment
metadata:
  labels:
    app: binkaga
  name: binkaga
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binkaga
  strategy: {}
  template:
    metadata:
      labels:
        app: binkaga
    spec:
      containers:
      - image: binkaga:1.0-prd
        name: binkaga
        ports:
        - containerPort: 3000
        resources:
          limits: 
            cpu: 300m
            memory: 1000Mi
          requests: 
            cpu: 10m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: binkaga
  name: binkaga
  namespace: prod
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: binkaga

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: binkaga-prd
  namespace: prod
spec:
  ingressClassName: nginx
  rules:
  - host: demo.localprod.me
    http:
      paths:
      - backend:
          service:
            name: binkaga
            port:
              number: 80
        path: /
        pathType: Prefix